// DO NOT EDIT THIS FILE
// GENERATED ON 2024-05-04 01:07:02

package love.Love;

import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

@:native("love.Love")
extern class Love {

	public static function getVersion(): Version;

	public static function hasDeprecationOutput(): Bool;

	@:overload
	public static function isVersionCompatible(version:String): Bool;

	@:overload
	public static function isVersionCompatible(major:Float, minor:Float, revision:Float): Bool;

	public static function setDeprecationOutput(enable:Bool): Void;

}

extern public class Version {
	public var major:Float;
	public var minor:Float;
	public var revision:Float;
	public var codename:String;
}

extern class Data extends Object {

	public static function clone(): Data;

	public static function getFFIPointer(): Cdata;

	public static function getPointer(): UserData;

	public static function getSize(): Float;

	public static function getString(): String;

}

extern class Object {

	public static function release(): Bool;

	public static function type(): String;

	public static function typeOf(name:String): Bool;

}

