// DO NOT EDIT THIS FILE
// GENERATED ON 2024-05-04 00:10:54

package love.touch;

import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

@:native("love.touch")
extern class Touch {

	public static function getPosition(id:UserData): Position;

	public static function getPressure(id:UserData): Float;

	public static function getTouches(): Table<Dynamic,Dynamic>;

}

extern public class Position {
	public var x:Float;
	public var y:Float;
}

