// DO NOT EDIT THIS FILE
// GENERATED ON 2024-05-04 01:07:02

package love.video;

import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

@:native("love.video")
extern class Video {

	@:overload
	public static function newVideoStream(filename:String): VideoStream;

	@:overload
	public static function newVideoStream(file:File): VideoStream;

}

extern class VideoStream extends Object {

	public static function getFilename(): String;

	public static function isPlaying(): Bool;

	public static function pause(): Void;

	public static function play(): Void;

	public static function rewind(): Void;

	public static function seek(offset:Float): Void;

	public static function tell(): Float;

}

