// DO NOT EDIT THIS FILE
// GENERATED ON 2024-05-04 09:34:57

package love;

import lua.Table;
@:native("love.system")
extern class System {

	public static function getClipboardText(): String;

	public static function getOS(): String;

	public static function getPowerInfo(): PowerInfo;

	public static function getProcessorCount(): Float;

	public static function hasBackgroundMusic(): Bool;

	public static function openURL(url:String): Bool;

	public static function setClipboardText(text:String): Void;

	public static function vibrate(seconds:Float = 0.5): Void;

}

extern class PowerInfo {
	public var state:PowerState;
	public var percent:Float;
	public var seconds:Float;
}

enum PowerState {
	Unknown;
	Battery;
	Nobattery;
	Charging;
	Charged;
}

