// DO NOT EDIT THIS FILE
// GENERATED ON 2024-05-04 09:34:57

package love;

import lua.Table;
@:native("love.timer")
extern class Timer {

	public static function getAverageDelta(): Float;

	public static function getDelta(): Float;

	public static function getFPS(): Float;

	public static function getTime(): Float;

	public static function sleep(s:Float): Void;

	public static function step(): Float;

}

