/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-07-23 23:52:48
 */

package love2d;

import lua.Table;
import lua.UserData;

@:native("love.event")
extern class LoveEvent {


	@:overload(function (exitstatus:Float):Void {})
	public static function quit('restart':String):Void;

	public static function push(n:Event, a:Dynamic, b:Dynamic, c:Dynamic, d:Dynamic, e:Dynamic, f:Dynamic, ...varargs:Dynamic):Void;

	public static function pump():Void;

	public static function wait():Array<Dynamic>;

	public static function poll():Dynamic;

	public static function clear():Void;

}

extern enum Event {
	FOCUS;
	JOYSTICKPRESSED;
	JOYSTICKRELEASED;
	KEYPRESSED;
	KEYRELEASED;
	MOUSEPRESSED;
	MOUSERELEASED;
	QUIT;
	RESIZE;
	VISIBLE;
	MOUSEFOCUS;
	THREADERROR;
	JOYSTICKADDED;
	JOYSTICKREMOVED;
	JOYSTICKAXIS;
	JOYSTICKHAT;
	GAMEPADPRESSED;
	GAMEPADRELEASED;
	GAMEPADAXIS;
	TEXTINPUT;
	MOUSEMOVED;
	LOWMEMORY;
	TEXTEDITED;
	WHEELMOVED;
	TOUCHPRESSED;
	TOUCHRELEASED;
	TOUCHMOVED;
	DIRECTORYDROPPED;
	FILEDROPPED;
	JP;
	JR;
	KP;
	KR;
	MP;
	MR;
	Q;
	F;
}

