/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-07-23 23:52:48
 */

package love2d;

import lua.Table;
import lua.UserData;
import love2d.Love.Object;
import love2d.Image.ImageData;
import love2d.FileSystem.FileData;
import love2d.Love.Data;

@:multiReturn
extern class GlyphDataDimensions {

	public var height:Float;
	public var width:Float;

}

extern class GlyphData extends Data {


	function getGlyph():Float;

	function getFormat():Dynamic;

	function getDimensions():GlyphDataDimensions;

	function getBearing():GlyphDataBearing;

	function new():Void;

	function getGlyphString():String;

	function getHeight():Float;

	function getBoundingBox():GlyphDataBoundingBox;

	function getAdvance():Float;

	function getWidth():Float;

}

@:multiReturn
extern class GlyphDataBoundingBox {

	public var height:Float;
	public var x:Float;
	public var width:Float;
	public var y:Float;

}

extern class Rasterizer extends Object {


	function getLineHeight():Float;

	function getGlyphCount():Float;

	function hasGlyphs(glyph1:Dynamic, glyph2:Dynamic, ...varargs:Dynamic):Bool;

	@:overload(function (glyph:String):GlyphData {})
	function getGlyphData(glyphNumber:Float):GlyphData;

	function getAscent():Float;

	function new():Void;

	function getHeight():Float;

	function getDescent():Float;

	function getAdvance():Float;

}

@:native("love.font")
extern class LoveFont {


	@:overload(function (size:Float, hinting:HintingMode, dpiscale:Float):Rasterizer {})
	@:overload(function (fileName:String, size:Float, hinting:HintingMode, dpiscale:Float):Rasterizer {})
	public static function newTrueTypeRasterizer(fileData:FileData, size:Float, hinting:HintingMode, dpiscale:Float):Rasterizer;

	@:overload(function (filename:String):Rasterizer {})
	@:overload(function (data:FileData):Rasterizer {})
	@:overload(function (size:Float, hinting:HintingMode, dpiscale:Float):Rasterizer {})
	@:overload(function (fileName:String, size:Float, hinting:HintingMode, dpiscale:Float):Rasterizer {})
	@:overload(function (fileData:FileData, size:Float, hinting:HintingMode, dpiscale:Float):Rasterizer {})
	@:overload(function (imageData:ImageData, glyphs:String, dpiscale:Float):Rasterizer {})
	public static function newRasterizer(fileName:String, glyphs:String, dpiscale:Float):Rasterizer;

	public static function newImageRasterizer(imageData:ImageData, glyphs:String, extraSpacing:Float, dpiscale:Float):Rasterizer;

	public static function newGlyphData(rasterizer:Rasterizer, glyph:Float):Void;

	@:overload(function (imageData:ImageData, glyphs:String, dpiscale:Float):Rasterizer {})
	public static function newBMFontRasterizer(fileName:String, glyphs:String, dpiscale:Float):Rasterizer;

}

@:multiReturn
extern class GlyphDataBearing {

	public var bx:Float;
	public var by:Float;

}

extern enum HintingMode {
	NORMAL;
	LIGHT;
	MONO;
	NONE;
}

