/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-07-24 00:05:11
 */

package love2d;

import lua.Table;
import lua.UserData;
import love2d.Love.Object;

@:native("love.joystick")
extern class LoveJoystick {


	@:overload(function (guid:String, button:GamepadButton, inputtype:JoystickInputType, inputindex:Float, hatdir:JoystickHat):Bool {})
	public static function setGamepadMapping(guid:String, axis:GamepadAxis, inputtype:JoystickInputType, inputindex:Float, hatdir:JoystickHat):Bool;

	@:overload(function (filename:String):String {})
	public static function saveGamepadMappings():String;

	@:overload(function (filename:String):Void {})
	public static function loadGamepadMappings(mappings:String):Void;

	public static function getJoysticks():Table<Dynamic,Dynamic>;

	public static function getJoystickCount():Float;

	public static function getGamepadMappingString(guid:String):String;

}

@:multiReturn
extern class JoystickVibration {

	public var right:Float;
	public var left:Float;

}

@:multiReturn
extern class JoystickID {

	public var instanceid:Float;
	public var id:Float;

}

@:multiReturn
extern class JoystickGamepadMapping {

	public var inputtype:JoystickInputType;
	public var inputindex:Float;
	public var hatdirection:JoystickHat;

}

@:multiReturn
extern class JoystickDeviceInfo {

	public var vendorID:Float;
	public var productVersion:Float;
	public var productID:Float;

}

@:multiReturn
extern class JoystickAxes {

	public var axisDirN:Float;
	public var axisDir2:Float;
	public var axisDir1:Float;

}

extern class Joystick extends Object {


	@:overload(function (left:Float, right:Float):Bool {})
	@:overload(function ():Bool {})
	function setVibration(left:Float, right:Float, duration:Float):Bool;

	function new():Void;

	function isVibrationSupported():Bool;

	function isGamepadDown(buttonN:GamepadButton):Bool;

	function isGamepad():Bool;

	function isDown(buttonN:Float):Bool;

	function isConnected():Bool;

	function getVibration():JoystickVibration;

	function getName():String;

	function getID():JoystickID;

	function getHatCount():Float;

	function getHat(hat:Float):JoystickHat;

	function getGamepadMappingString():String;

	@:overload(function (axis:GamepadAxis):JoystickGamepadMapping {})
	function getGamepadMapping(button:GamepadButton):JoystickGamepadMapping;

	function getGamepadAxis(axis:GamepadAxis):Float;

	function getGUID():String;

	function getDeviceInfo():JoystickDeviceInfo;

	function getButtonCount():Float;

	function getAxisCount():Float;

	function getAxis(axis:Float):Float;

	function getAxes():JoystickAxes;

}

extern enum JoystickInputType {
	AXIS;
	BUTTON;
	HAT;
}

extern enum JoystickHat {
	C;
	D;
	L;
	LD;
	LU;
	R;
	RD;
	RU;
	U;
}

extern enum GamepadButton {
	A;
	B;
	X;
	Y;
	BACK;
	GUIDE;
	START;
	LEFTSTICK;
	RIGHTSTICK;
	LEFTSHOULDER;
	RIGHTSHOULDER;
	DPUP;
	DPDOWN;
	DPLEFT;
	DPRIGHT;
}

extern enum GamepadAxis {
	LEFTX;
	LEFTY;
	RIGHTX;
	RIGHTY;
	TRIGGERLEFT;
	TRIGGERRIGHT;
}

