/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-07-23 23:52:48
 */

package love2d;

import lua.Table;
import lua.UserData;
import love2d.FileSystem.File;
import love2d.Love.Object;
import love2d.Love.Data;

extern class Decoder extends Object {


	function getDuration():Float;

	function decode():SoundData;

	function getBitDepth():Float;

	function getSampleRate():Float;

	function new():Void;

	function getChannelCount():Float;

	function clone():Decoder;

	function seek(offset:Float):Void;

}

@:native("love.sound")
extern class LoveSound {


	@:overload(function (filename:String):SoundData {})
	@:overload(function (file:File):SoundData {})
	@:overload(function (decoder:Decoder):SoundData {})
	public static function newSoundData(samples:Float, rate:Float, bits:Float, channels:Float):SoundData;

	@:overload(function (file:File, buffer:Float):Decoder {})
	public static function newDecoder(filename:String, buffer:Float):Decoder;

}

extern class SoundData extends Data {


	@:overload(function (i:Float, sample:Float):Void {})
	function setSample(i:Float, channel:Float, sample:Float):Void;

	function getDuration():Float;

	@:overload(function (i:Float):Float {})
	function getSample(i:Float, channel:Float):Float;

	function getBitDepth():Float;

	function getSampleRate():Float;

	function new():Void;

	function getSampleCount():Float;

	function getChannelCount():Float;

}

