/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-07-24 00:24:06
 */

package love2d;

import lua.Table;
import lua.UserData;
import love2d.Love.Object;
import love2d.FileSystem.FileData;

extern class Thread extends Object {


	function wait():Void;

	@:overload(function ():Void {})
	function start(...varargs:Dynamic):Void;

	function new():Void;

	function isRunning():Bool;

	function getError():String;

}

@:native("love.thread")
extern class LoveThread {


	@:overload(function (filename:String):Thread {})
	@:overload(function (fileData:FileData):Thread {})
	public static function newThread(codestring:String):Thread;

	public static function newChannel():Channel;

	public static function getChannel(name:String):Channel;

}

extern class Channel extends Object {


	@:overload(function (value:Dynamic):Bool {})
	function supply(value:Dynamic, timeout:Float):Bool;

	function push(value:Dynamic):Float;

	function pop():Dynamic;

	function performAtomic(func:Dynamic, ...varargs:Dynamic):Array<Dynamic>;

	function peek():Dynamic;

	function new():Void;

	function hasRead(id:Float):Bool;

	function getCount():Float;

	@:overload(function ():Dynamic {})
	function demand(timeout:Float):Dynamic;

	function clear():Void;

}

