/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-07-23 23:52:48
 */

package love2d;

import lua.Table;
import lua.UserData;

@:native("love.touch")
extern class LoveTouch {


	public static function getTouches():Table<Dynamic,Dynamic>;

	public static function getPressure(id:UserData):Float;

	public static function getPosition(id:UserData):TouchPosition;

}

@:multiReturn
extern class TouchPosition {

	public var x:Float;
	public var y:Float;

}

