/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.4.
 * Do not modify this file directly.
 * 2024-05-05 16:52:58
 */

package love;

@:native("love.data")
extern class Data {

	@:overload
	public static function compress(container:ContainerType, format:CompressedDataFormat, rawstring:String, level:Float):CompressedData or string;

	@:overload
	public static function compress(container:ContainerType, format:CompressedDataFormat, data:Data, level:Float):CompressedData or string;

	@:overload
	public static function decode(container:ContainerType, format:EncodeFormat, sourceString:String):ByteData or string;

	@:overload
	public static function decode(container:ContainerType, format:EncodeFormat, sourceData:Data):ByteData or string;

	@:overload
	public static function decompress(container:ContainerType, compressedData:CompressedData):Data or string;

	@:overload
	public static function decompress(container:ContainerType, format:CompressedDataFormat, compressedString:String):Data or string;

	@:overload
	public static function decompress(container:ContainerType, format:CompressedDataFormat, data:Data):Data or string;

	@:overload
	public static function encode(container:ContainerType, format:EncodeFormat, sourceString:String, linelength:Float):ByteData or string;

	@:overload
	public static function encode(container:ContainerType, format:EncodeFormat, sourceData:Data, linelength:Float):ByteData or string;

	public static function getPackedSize(format:String):Float;

	@:overload
	public static function hash(hashFunction:HashFunction, string:String):String;

	@:overload
	public static function hash(hashFunction:HashFunction, data:Data):String;

	@:overload
	public static function newByteData(datastring:String):ByteData;

	@:overload
	public static function newByteData(Data:Data, offset:Float, size:Float):ByteData;

	@:overload
	public static function newByteData(size:Float):ByteData;

	public static function newDataView(data:Data, offset:Float, size:Float):Data;

	public static function pack(container:ContainerType, format:String, v1:Number or boolean or string, ...:Number or boolean or string):Data or string;

	@:overload
	public static function unpack(format:String, datastring:String, pos:Float):UnpackResult;

	@:overload
	public static function unpack(format:String, data:Data, pos:Float):UnpackResult;

}

extern class ByteData {

}

extern class CompressedData {

	public static function getFormat():CompressedDataFormat;

}

extern enum CompressedDataFormat {
	LZ4;
	ZLIB;
	GZIP;
	DEFLATE;
}

extern enum ContainerType {
	DATA;
	STRING;
}

extern enum EncodeFormat {
	BASE64;
	HEX;
}

extern enum HashFunction {
	MD5;
	SHA1;
	SHA224;
	SHA256;
	SHA384;
	SHA512;
}

extern class UnpackResult {

	public var v1:Number or boolean or string;
	public var ...:Number or boolean or string;
	public var index:Float;

}

