/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.4.
 * Do not modify this file directly.
 * 2024-05-06 00:46:03
 */

package love;

import lua.Table;
import love.Love2D.Object;
import love.Love2D.Data;

extern class ByteData extends Object {
}

extern class CompressedData extends Data {
	public static function getFormat():CompressedDataFormat;
}

extern class DataModule {
	public static function compress(container:ContainerType, format:CompressedDataFormat, rawstring:String, level:Float):String;
	public static function compress(container:ContainerType, format:CompressedDataFormat, data:Data, level:Float):String;
	public static function decode(container:ContainerType, format:EncodeFormat, sourceString:String):String;
	public static function decode(container:ContainerType, format:EncodeFormat, sourceData:Data):String;
	public static function decompress(container:ContainerType, compressedData:CompressedData):String;
	public static function decompress(container:ContainerType, format:CompressedDataFormat, compressedString:String):String;
	public static function decompress(container:ContainerType, format:CompressedDataFormat, data:Data):String;
	public static function encode(container:ContainerType, format:EncodeFormat, sourceString:String, linelength:Float):String;
	public static function encode(container:ContainerType, format:EncodeFormat, sourceData:Data, linelength:Float):String;
	public static function getPackedSize(format:String):Float;
	public static function hash(hashFunction:HashFunction, string:String):String;
	public static function hash(hashFunction:HashFunction, data:Data):String;
	public static function newByteData(datastring:String):ByteData;
	public static function newByteData(Data:Data, offset:Float, size:Float):ByteData;
	public static function newByteData(size:Float):ByteData;
	public static function newDataView(data:Data, offset:Float, size:Float):Data;
	public static function pack(container:ContainerType, format:String, v1:String, ...varargs:String):String;
	public static function unpack(format:String, datastring:String, pos:Float):UnpackResult;
	public static function unpack(format:String, data:Data, pos:Float):UnpackResult;
}

extern class UnpackResult {
	public var v1:String;
	// Skipping field ... of type String.
	public var index:Float;
}

extern enum ContainerType {
	DATA;
	STRING;
}

extern enum EncodeFormat {
	BASE64;
	HEX;
}

extern enum HashFunction {
	MD5;
	SHA1;
	SHA224;
	SHA256;
	SHA384;
	SHA512;
}

extern enum CompressedDataFormat {
	LZ4;
	ZLIB;
	GZIP;
	DEFLATE;
}

