/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.4.
 * Do not modify this file directly.
 * 2024-05-05 16:52:58
 */

package love;

@:native("love.image")
extern class Image {

	@:overload
	public static function isCompressed(filename:String):Bool;

	@:overload
	public static function isCompressed(fileData:FileData):Bool;

	@:overload
	public static function newCompressedData(filename:String):CompressedImageData;

	@:overload
	public static function newCompressedData(fileData:FileData):CompressedImageData;

	@:overload
	public static function newImageData(width:Float, height:Float):ImageData;

	@:overload
	public static function newImageData(width:Float, height:Float, format:PixelFormat, data:String):ImageData;

	@:overload
	public static function newImageData(width:Float, height:Float, data:String):ImageData;

	@:overload
	public static function newImageData(filename:String):ImageData;

	@:overload
	public static function newImageData(filedata:FileData):ImageData;

}

extern class CompressedImageData {

	@:overload
	public static function getDimensions():Dimensions;

	@:overload
	public static function getDimensions(level:Float):Dimensions;

	public static function getFormat():CompressedImageFormat;

	@:overload
	public static function getHeight():Float;

	@:overload
	public static function getHeight(level:Float):Float;

	public static function getMipmapCount():Float;

	@:overload
	public static function getWidth():Float;

	@:overload
	public static function getWidth(level:Float):Float;

}

extern class ImageData {

	@:overload
	public static function encode(format:ImageFormat, filename:String):FileData;

	@:overload
	public static function encode(outFile:String):Void;

	@:overload
	public static function encode(outFile:String, format:ImageFormat):Void;

	public static function getDimensions():Dimensions;

	public static function getHeight():Float;

	public static function getPixel(x:Float, y:Float):Pixel;

	public static function getWidth():Float;

	public static function mapPixel(pixelFunction:Function, x:Float, y:Float, width:Float, height:Float):Void;

	public static function paste(source:ImageData, dx:Float, dy:Float, sx:Float, sy:Float, sw:Float, sh:Float):Void;

	@:overload
	public static function setPixel(x:Float, y:Float, r:Float, g:Float, b:Float, a:Float):Void;

	@:overload
	public static function setPixel(x:Float, y:Float, color:Table<Dynamic,Dynamic>):Void;

	public static function getFormat():PixelFormat;

}

extern enum CompressedImageFormat {
	DXT1;
	DXT3;
	DXT5;
	BC4;
	BC4S;
	BC5;
	BC5S;
	BC6H;
	BC6HS;
	BC7;
	ETC1;
	ETC2RGB;
	ETC2RGBA;
	ETC2RGBA1;
	EACR;
	EACRS;
	EACRG;
	EACRGS;
	PVR1RGB2;
	PVR1RGB4;
	PVR1RGBA2;
	PVR1RGBA4;
	ASTC4X4;
	ASTC5X4;
	ASTC5X5;
	ASTC6X5;
	ASTC6X6;
	ASTC8X5;
	ASTC8X6;
	ASTC8X8;
	ASTC10X5;
	ASTC10X6;
	ASTC10X8;
	ASTC10X10;
	ASTC12X10;
	ASTC12X12;
}

extern enum ImageFormat {
	TGA;
	PNG;
	JPG;
	BMP;
}

extern enum PixelFormat {
	UNKNOWN;
	NORMAL;
	HDR;
	R8;
	RG8;
	RGBA8;
	SRGBA8;
	R16;
	RG16;
	RGBA16;
	R16F;
	RG16F;
	RGBA16F;
	R32F;
	RG32F;
	RGBA32F;
	LA8;
	RGBA4;
	RGB5A1;
	RGB565;
	RGB10A2;
	RG11B10F;
	STENCIL8;
	DEPTH16;
	DEPTH24;
	DEPTH32F;
	DEPTH24STENCIL8;
	DEPTH32FSTENCIL8;
	DXT1;
	DXT3;
	DXT5;
	BC4;
	BC4S;
	BC5;
	BC5S;
	BC6H;
	BC6HS;
	BC7;
	ETC1;
	ETC2RGB;
	ETC2RGBA;
	ETC2RGBA1;
	EACR;
	EACRS;
	EACRG;
	EACRGS;
	PVR1RGB2;
	PVR1RGB4;
	PVR1RGBA2;
	PVR1RGBA4;
	ASTC4X4;
	ASTC5X4;
	ASTC5X5;
	ASTC6X5;
	ASTC6X6;
	ASTC8X5;
	ASTC8X6;
	ASTC8X8;
	ASTC10X5;
	ASTC10X6;
	ASTC10X8;
	ASTC10X10;
	ASTC12X10;
	ASTC12X12;
}

extern class Dimensions {

	public var width:Float;
	public var height:Float;

}

extern class Pixel {

	public var r:Float;
	public var g:Float;
	public var b:Float;
	public var a:Float;

}

