/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 18:21:25
 */

package love;

import lua.Table;
import lua.UserData;
import love.Love2D.Object;

@:multiReturn
extern class Vibration {

	public var left:Float;
	public var right:Float;
}

extern class Joystick extends Object {

	function getAxes():Axes;

	function getAxis(axis:Float):Float;

	function getAxisCount():Float;

	function getButtonCount():Float;

	function getDeviceInfo():DeviceInfo;

	function getGUID():String;

	function getGamepadAxis(axis:GamepadAxis):Float;

	@:overload(function (axis:GamepadAxis):GamepadMapping {})
	function getGamepadMapping(button:GamepadButton):GamepadMapping;

	function getGamepadMappingString():String;

	function getHat(hat:Float):JoystickHat;

	function getHatCount():Float;

	function getID():ID;

	function getName():String;

	function getVibration():Vibration;

	function isConnected():Bool;

	function isDown(buttonN:Float):Bool;

	function isGamepad():Bool;

	function isGamepadDown(buttonN:GamepadButton):Bool;

	function isVibrationSupported():Bool;

	@:overload(function (left:Float, right:Float):Bool {})
	@:overload(function ():Bool {})
	function setVibration(left:Float, right:Float, duration:Float):Bool;

}

@:multiReturn
extern class ID {

	public var id:Float;
	public var instanceid:Float;
}

@:multiReturn
extern class Axes {

	public var axisDir1:Float;
	public var axisDir2:Float;
	public var axisDirN:Float;
}

@:multiReturn
extern class GamepadMapping {

	public var inputtype:JoystickInputType;
	public var inputindex:Float;
	public var hatdirection:JoystickHat;
}

extern class JoystickModule {

	public static function getGamepadMappingString(guid:String):String;

	public static function getJoystickCount():Float;

	public static function getJoysticks():Table<Dynamic,Dynamic>;

	@:overload(function (filename:String):Void {})
	public static function loadGamepadMappings(mappings:String):Void;

	@:overload(function (filename:String):String {})
	public static function saveGamepadMappings():String;

	@:overload(function (guid:String, button:GamepadButton, inputtype:JoystickInputType, inputindex:Float, hatdir:JoystickHat):Bool {})
	public static function setGamepadMapping(guid:String, axis:GamepadAxis, inputtype:JoystickInputType, inputindex:Float, hatdir:JoystickHat):Bool;

}

@:multiReturn
extern class DeviceInfo {

	public var vendorID:Float;
	public var productID:Float;
	public var productVersion:Float;
}

extern enum GamepadButton {
	A;
	B;
	X;
	Y;
	BACK;
	GUIDE;
	START;
	LEFTSTICK;
	RIGHTSTICK;
	LEFTSHOULDER;
	RIGHTSHOULDER;
	DPUP;
	DPDOWN;
	DPLEFT;
	DPRIGHT;
}

extern enum JoystickHat {
	C;
	D;
	L;
	LD;
	LU;
	R;
	RD;
	RU;
	U;
}

extern enum GamepadAxis {
	LEFTX;
	LEFTY;
	RIGHTX;
	RIGHTY;
	TRIGGERLEFT;
	TRIGGERRIGHT;
}

extern enum JoystickInputType {
	AXIS;
	BUTTON;
	HAT;
}

