/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 18:21:25
 */

package love;

import lua.Table;
import lua.UserData;

@:multiReturn
extern class Version {

	public var major:Float;
	public var minor:Float;
	public var revision:Float;
	public var codename:String;
}

extern class Love2DModule {

	public static function getVersion():Version;

	public static function hasDeprecationOutput():Bool;

	@:overload(function (version:String):Bool {})
	public static function isVersionCompatible(major:Float, minor:Float, revision:Float):Bool;

	public static function setDeprecationOutput(enable:Bool):Void;

}

extern class Object {

	function release():Bool;

	function type():String;

	function typeOf(name:String):Bool;

}

extern class Data extends Object {

	function clone():Data;

	function getFFIPointer():Dynamic;

	function getPointer():UserData;

	function getSize():Float;

	function getString():String;

}

