/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 19:31:28
 */

package love;

import lua.Table;
import lua.UserData;
import love.Love2D.Object;
import love.FileSystem.FileData;
import love.Image.ImageData;

@:native("love.mouse")
extern class MouseModule {

	public static function getCursor():Dynamic;

	public static function getPosition():MousePosition;

	public static function getRelativeMode():Bool;

	public static function getSystemCursor(ctype:Dynamic):Dynamic;

	public static function getX():Float;

	public static function getY():Float;

	public static function isCursorSupported():Bool;

	public static function isDown(button:Float, ...varargs:Float):Bool;

	public static function isGrabbed():Bool;

	public static function isVisible():Bool;

	@:overload(function (imageData:ImageData, hotx:Float, hoty:Float):Dynamic {})
	@:overload(function (filename:String, hotx:Float, hoty:Float):Dynamic {})
	public static function newCursor(fileData:FileData, hotx:Float, hoty:Float):Dynamic;

	@:overload(function (cursor:Dynamic):Void {})
	public static function setCursor():Void;

	public static function setGrabbed(grab:Bool):Void;

	public static function setPosition(x:Float, y:Float):Void;

	public static function setRelativeMode(enable:Bool):Void;

	public static function setVisible(visible:Bool):Void;

	public static function setX(x:Float):Void;

	public static function setY(y:Float):Void;

}

@:multiReturn
extern class MousePosition {

	public var x:Float;
	public var y:Float;
}

extern class Cursor extends Object {

	function getType():Dynamic;

}

extern enum CursorType {
	IMAGE;
	ARROW;
	IBEAM;
	WAIT;
	WAITARROW;
	CROSSHAIR;
	SIZENWSE;
	SIZENESW;
	SIZEWE;
	SIZENS;
	SIZEALL;
	NO;
	HAND;
}

