/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.4.
 * Do not modify this file directly.
 * 2024-05-06 00:46:03
 */

package love;

import lua.Table;
import love.Filesystem.File;
import love.Love2D.Object;
import love.Love2D.Data;

extern class Decoder extends Object {
	public static function clone():Decoder;
	public static function decode():SoundData;
	public static function getBitDepth():Float;
	public static function getChannelCount():Float;
	public static function getDuration():Float;
	public static function getSampleRate():Float;
	public static function seek(offset:Float):Void;
}

extern class SoundModule {
	public static function newDecoder(file:File, buffer:Float):Decoder;
	public static function newDecoder(filename:String, buffer:Float):Decoder;
	public static function newSoundData(filename:String):SoundData;
	public static function newSoundData(file:File):SoundData;
	public static function newSoundData(decoder:Decoder):SoundData;
	public static function newSoundData(samples:Float, rate:Float, bits:Float, channels:Float):SoundData;
}

extern class SoundData extends Data {
	public static function getBitDepth():Float;
	public static function getChannelCount():Float;
	public static function getDuration():Float;
	public static function getSample(i:Float):Float;
	public static function getSample(i:Float, channel:Float):Float;
	public static function getSampleCount():Float;
	public static function getSampleRate():Float;
	public static function setSample(i:Float, sample:Float):Void;
	public static function setSample(i:Float, channel:Float, sample:Float):Void;
}

