/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 20:41:36
 */

package love;

import lua.Table;
import lua.UserData;

@:native("love.system")
extern class SystemModule {

	public static function openURL(url:String):Bool;

	public static function getPowerInfo():SystemPowerInfo;

	public static function getOS():String;

	public static function vibrate(seconds:Float):Void;

	public static function getProcessorCount():Float;

	public static function getClipboardText():String;

	public static function setClipboardText(text:String):Void;

	public static function hasBackgroundMusic():Bool;

}

@:multiReturn
extern class SystemPowerInfo {

	public var percent:Float;
	public var seconds:Float;
	public var state:PowerState;
}

extern enum PowerState {
	UNKNOWN;
	BATTERY;
	NOBATTERY;
	CHARGING;
	CHARGED;
}

