/*
 * This file was generated by the LOVE2D Haxe bindings generator.
 * Do not modify this file directly.
 * 2024-05-04 23:35:07
 */

package love;

@:native("love.system")
extern class System {

	public static function getClipboardText():String;

	public static function getOS():String;

	public static function getPowerInfo():PowerInfo;

	public static function getProcessorCount():Float;

	public static function hasBackgroundMusic():Bool;

	public static function openURL(url:String):Bool;

	public static function setClipboardText(text:String):Void;

	public static function vibrate(seconds:Float):Void;

}

extern enum PowerState {
	UNKNOWN;
	BATTERY;
	NOBATTERY;
	CHARGING;
	CHARGED;
}

extern class PowerInfo {

	public var state:PowerState;
	public var percent:Float;
	public var seconds:Float;

}

