/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 20:41:36
 */

package love;

import lua.Table;
import lua.UserData;
import love.Love2D.Object;
import love.FileSystem.FileData;

@:multiReturn
extern class ChannelPerformAtomicResult {

	public var ret1:Dynamic;
	// Skipping field ... of type Dynamic.
}

@:native("love.thread")
extern class ThreadModule {

	public static function newChannel():Channel;

	@:overload(function (filename:String):Thread {})
	@:overload(function (fileData:FileData):Thread {})
	public static function newThread(codestring:String):Thread;

	public static function getChannel(name:String):Channel;

}

extern class Thread extends Object {

	@:overload(function ():Void {})
	function start(arg1:Dynamic, arg2:Dynamic, ...varargs:Dynamic):Void;

	function wait():Void;

	function new():Void;

	function isRunning():Bool;

	function getError():String;

}

extern class Channel extends Object {

	function push(value:Dynamic):Float;

	@:overload(function ():Dynamic {})
	function demand(timeout:Float):Dynamic;

	function pop():Dynamic;

	function peek():Dynamic;

	@:overload(function (value:Dynamic):Bool {})
	function supply(value:Dynamic, timeout:Float):Bool;

	function new():Void;

	function performAtomic(func:Dynamic, arg1:Dynamic, ...varargs:Dynamic):ChannelPerformAtomicResult;

	function hasRead(id:Float):Bool;

	function getCount():Float;

	function clear():Void;

}

