/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 19:31:28
 */

package love;

import lua.Table;
import lua.UserData;

@:native("love.timer")
extern class TimerModule {

	public static function getAverageDelta():Float;

	public static function getDelta():Float;

	public static function getFPS():Float;

	public static function getTime():Float;

	public static function sleep(s:Float):Void;

	public static function step():Float;

}

