/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.4.
 * Do not modify this file directly.
 * 2024-05-06 00:46:03
 */

package love;

import lua.Table;

extern class TimerModule {
	public static function getAverageDelta():Float;
	public static function getDelta():Float;
	public static function getFPS():Float;
	public static function getTime():Float;
	public static function sleep(s:Float):Void;
	public static function step():Float;
}

