/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 18:21:25
 */

package love;

import lua.Table;
import lua.UserData;

extern class TouchModule {

	public static function getPosition(id:UserData):Position;

	public static function getPressure(id:UserData):Float;

	public static function getTouches():Table<Dynamic,Dynamic>;

}

@:multiReturn
extern class Position {

	public var x:Float;
	public var y:Float;
}

