/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 20:41:36
 */

package love;

import lua.Table;
import lua.UserData;

@:native("love.touch")
extern class TouchModule {

	public static function getTouches():Table<Dynamic,Dynamic>;

	public static function getPressure(id:UserData):Float;

	public static function getPosition(id:UserData):TouchPosition;

}

@:multiReturn
extern class TouchPosition {

	public var x:Float;
	public var y:Float;
}

