/*
 * This file was generated by the LOVE2D Haxe bindings generator.
 * Do not modify this file directly.
 * 2024-05-04 23:35:07
 */

package love;

@:native("love.video")
extern class Video {

	public static function newVideoStream(filename:String):VideoStream;

	public static function newVideoStream(file:File):VideoStream;

}

extern class VideoStream {

	public static function getFilename():String;

	public static function isPlaying():Bool;

	public static function pause():Void;

	public static function play():Void;

	public static function rewind():Void;

	public static function seek(offset:Float):Void;

	public static function tell():Float;

}

