/*
 * This file was generated by the LOVE2D Haxe bindings generator for Love2D v11.5.
 * Do not modify this file directly.
 * 2024-05-12 20:41:36
 */

package love;

import lua.Table;
import lua.UserData;
import love.FileSystem.File;
import love.Love2D.Object;

extern class VideoStream extends Object {

	function rewind():Void;

	function getFilename():String;

	function new():Void;

	function pause():Void;

	function tell():Float;

	function seek(offset:Float):Void;

	function play():Void;

	function isPlaying():Bool;

}

@:native("love.video")
extern class VideoModule {

	@:overload(function (filename:String):VideoStream {})
	public static function newVideoStream(file:File):VideoStream;

}

