name: CI

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Lua
          uses: leafo/gh-actions-lua@v10  
          with:
            luaVersion: luajit  
        - name: run tests
          run: lua build.lua