name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: latest
    - name: Run Generator
      run: haxe lovehaxe.hxml
    - name: Release Please
      uses: googleapis/release-please-action@v4
      with:
        release-type: simple
